### PR TITLE
Added number shortening

### PR DESCRIPTION
**Pull request by shivam212**
**Description**

Added a number shortening function as needed, works with a newly added --long-stats flag.

**Context**

Adds the enhancement as in issue #40 .

**More details**
Rounding up and if the value after rounding up is more than 1000, it's shortened.

Remember that your code will be checked by the black formatter, pylint, codespell, and pytest.

### CODE REVIEW

**Comment by hedythedev** [comment]
Thanks, I’m a bit busy at the moment, will get back you later

**Comment by hedythedev** [comment]
Oh meanwhile, would you mind adding a test for the shorten number function? Just add a `test_shorten_number` file and add a function named the same in the file, import the function and throw it some dummy numbers and make it shorten the number, use the assert keyword. You can check out test_search file for reference if you're stuck.

Then you can see if the test passes by running `python -m pytest` on the terminal

**Comment by shivam212** [comment]
Will do!

**Comment by shivam212** [comment]
@hedythedev done!

**Comment by hedythedev** [comment]
Everything looks good, I've just fixed formatting and the `6.0k to 6k` things. Should be ready to merge when I have time tomorrow, thanks for the contribution @shivam212!
If you have anything else to add, you can do so, because I might merge it tomorrow

**Pull request merged**
