### PR TITLE
Add spoken language

### LINKED ISSUE #45: Filtering by spoken language (new option)
Currently we can only filter by language, date, and stars, we should also add `--spoken-language` option to filter by spoken language (Chinese, English, etc):
Screenshot_20200711_080341

Github API can probably filter it for us, if not, we might have to scrape it from the website. 
Remember to update the readme when adding a new option

### PR DESCRIPTION
**Pull request by Saif807380**
**Context**

Added filtering by language spoken as a new option. Resolves #45 

**Description**

Scraped GitHub Trending Page to allow filtering based on spoken languages. This option can be combined with filtering by programming languages, by number of stars, by limit of results, different layouts as well as asc/desc ordering of stars. Added the option with flags `--spoken-language` and `-S`. 

I went ahead with scraping as GitHub Search API has no query parameter or endpoint for filtering by spoken language. 

I have also added a json file that contains a list of all supported languages and their corresponding language codes. Also I have added the new feature to `README.md` file

Here's a preview of the option,

Screenshot 2020-07-20 at 14 00 17

I have used the `zh` language code, which stands for Chinese, in combination with other flags to display the results.

### CODE REVIEW

**Comment by Saif807380** [comment]
Please add the `spoken-languages.json` file to codespell skip list as it is trying to read the language codes as common English words hence PR is failing checks.

**Comment by Saif807380** [comment]
I have made all the mentioned changes.

**Comment by hedythedev** [comment]
use >= instead of == in requirements txt and setup.py would be better 🙂

**Comment by Saif807380** [comment]
Done

**Comment by hedythedev** [comment]
@allcontributors please add @Saif807380 for code and docs

**Pull request merged**
